### ISSUE TITLE
merge pull request to master

### ISSUE THREAD

**Issue by beelee1** [beelee1/world_war_ii_global#1]
@panther2
I think I screwed up somewhere. I can't merge my branch to the master. No merge button showed up.
edit: well idk what happened. I tried a few more times and it seems to have merged now.

**Comment by panther2** [comment]
@beelee1 
Looks good so far! Congrats.

**Comment by beelee1** [comment]
cool thanks for all your help panther

**Comment by panther2** [comment]
You're welcome :-)
